### PR TITLE
Authenticate NSURLRequest

### PR DESCRIPTION
**Pull request by fabiomassimo**
# Summary

Authenticate `NSURLRequest` as specified by OAuth 2.0 guidelines for token type _Bearer_.

The `Provider` exposes a convenience method that, in case the available token is expired, refreshes the token and then uses it to authenticate any `NSURLRequest`.
# Why

This feature give to the client an easy way to integrate a valid access token, retrieved via OAuth 2.0, in any `NSURLRequest` that the client might have created beforehand.
# Note

To improve test cases accuracy I needed to add a dependency for the test target: [OHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs).

I found the best way to do it via [Carthage](https://github.com/Carthage/Carthage). To get started run the shell script in the `bin` folder.

### CODE REVIEW

**Comment by fabiomassimo** [comment]
[WIP] to make Travis CI work.

First time I'm dealing with this. I hope to fix this soon.

**Comment by delba** [comment]
Thanks @fabiomassimo ! 

That's interesting but it makes too many assumptions for now... But that's definitely something I'll reconsider later. Sorry :/

**Comment by fabiomassimo** [comment]
Ok, when you'll have time I'd be happy to discuss with you these assumptions that you are concerned about such that maybe I can improve my PR.

Thank you.

**Comment by delba** [comment]
SwiftyOAuth focuses on authorization and obtaining token. What the user will do with this token is out of the scope of the lib.

There are other OAuth libs that provide authenticated requests (something along `provider.get(myURL, callback: myCallback)`) but I don't think it's a good design.

Moreover each provider has its own peculiarity: some ask you to pass the token in the query string, other in the header `Bearer abc123`. I once stumbled upon a provider that only recognized `bearer abc123` (lowercase `bearer`)...

For these reasons I prefer to leave this part to the SwiftyOAuth user.

**Comment by fabiomassimo** [comment]
Thank you for the explanation. It makes totally sense.

**Pull request closed without merging**
