### PR TITLE
Swift 3.0

### PR DESCRIPTION
**Pull request by fabiomassimo**
# Summary

Implementation for #13 
- [x] Add new grant type: http://oauth.net/grant_type/device/1.0
- [x] Handle new error cases: "authorisation_pending" , "slow_down", "code_expired"
- [x] Extend the Provider with support to request an access token with new grant type.

### CODE REVIEW

**Comment by fabiomassimo** [comment]
Why it has been closed without merge? Is it there something that must be improved?

**Comment by delba** [comment]
Oh sorry @fabiomassimo, it has been automatically closed because I renamed the `swift-3.0` branch to `master` and deleted it. Could you please make a new PR on master ?

**Comment by fabiomassimo** [comment]
No problem. It will be first thing tomorrow. 

Thanks for the update :)

**Comment by delba** [comment]
By the way, here is the API I want to have for the device flow: https://gist.github.com/delba/17ce1f5cd6a894fe0d3b07c7f1694bd9

I still haven't made up my mind on whether to include this flow in SwiftyOAuth or not but let me know what you think :)

**Pull request closed without merging**
